# Generated by Django 5.2.9 on 2025-12-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL метка')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название торта')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание вкуса')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('calories', models.PositiveIntegerField(help_text='Только цифра', verbose_name='Ккал (на 100г)')),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Белки (г)')),
                ('fats', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Жиры (г)')),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Углеводы (г)')),
                ('is_sugar_free', models.BooleanField(default=True, verbose_name='Без сахара')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Без глютена')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Веган')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (MYR)')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'ПП Десерт',
                'verbose_name_plural': 'ПП Десерты',
            },
        ),
    ]
