# Generated by Django 5.1.6 on 2025-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options_remove_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Наличные'), ('Card', 'Онлайн / Карта')], default='Cash', max_length=10),
        ),
    ]
